# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-lib:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start build for gadget"
      - run: yarn install
      - run: yarn build-lib
  build-app:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start build for triangle"
      - run: yarn install
      - run: yarn build-lib
      - run: yarn build-app
  build-gh:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start build for gh-render"
      - run: yarn install
      - run: yarn build-lib
      - run: yarn build-gh
  build-tm:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start build for todo-manager"
      - run: yarn install
      - run: yarn build-lib
      - run: yarn build-tm
  lint:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start lint"
      - run: yarn install
      - run: yarn lint
  stylelint:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start stylelint"
      - run: yarn install
      - run: yarn stylelint
  test-lib:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start test for gadget"
      - run: yarn install
      - run: yarn test-lib --watch=false --code-coverage
      - store_artifacts:
          path: coverage
  test-app:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start test for triangle"
      - run: yarn install
      - run: yarn build-lib
      - run: yarn test-app --watch=false --code-coverage
      - store_artifacts:
          path: coverage
  test-gh:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start test for gh-render"
      - run: yarn install
      - run: yarn build-lib
      - run: yarn test-gh --watch=false --code-coverage
      - store_artifacts:
          path: coverage
  test-tm:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start test for todo-manager"
      - run: yarn install
      - run: yarn build-lib
      - run: yarn test-tm --watch=false --code-coverage
      - store_artifacts:
          path: coverage
  e2e-app:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start e2e-app"
      - run: yarn install
      - run: yarn build-lib
      - run: yarn e2e-app
  e2e-gh:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start e2e-gh"
      - run: yarn install
      - run: yarn build-lib
      - run: yarn e2e-gh
  e2e-tm:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start e2e-tm"
      - run: yarn install
      - run: yarn build-lib
      - run: yarn e2e-tm
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-lib
      - build-app:
          requires:
            - build-lib
      - build-gh:
          requires:
            - build-lib
      - build-tm:
          requires:
            - build-lib
      - lint:
          requires:
            - build-app
      - stylelint:
          requires:
            - build-app
      - test-lib:
          requires:
            - build-lib
      - test-app:
          requires:
            - build-app
      - test-gh:
          requires:
            - build-gh
      - test-tm:
          requires:
            - build-tm
      - e2e-app:
          requires:
            - build-app
      - e2e-gh:
          requires:
            - build-gh
      - e2e-tm:
          requires:
            - build-tm
