# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers

    steps:
      - checkout
      - run: echo "Start build"
      - run: npm install
      - run: npm run build

  lint:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers

    steps:
      - checkout
      - run: echo "Start lint"
      - run: npm install
      - run: npm run lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint
          requires:
            - build
