# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-app:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start build for triangle"
      - run: yarn install
      - run: yarn build triangle
  build-lib:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start build for gadget"
      - run: yarn install
      - run: yarn build gadget
  lint:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start lint"
      - run: yarn install
      - run: yarn lint
  stylelint:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start stylelint"
      - run: yarn install
      - run: yarn stylelint
  test:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start test"
      - run: yarn install
      - run: yarn test --watch=false --code-coverage
      - store_artifacts:
          path: coverage
  e2e:
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - checkout
      - run: echo "Start e2e"
      - run: yarn install
      - run: yarn e2e
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-app
      - build-lib
      - lint:
          requires:
            - build-app
      - stylelint:
          requires:
            - build-app
      - test:
          requires:
            - build-app
      - e2e:
          requires:
            - build-app
