# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install-packages:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start installing the packages"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

  build-lib:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start build for gadget"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
  build-storybook:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start build for Storybook"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn build-storybook
      - store_artifacts:
          path: storybook-static
  build-app:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start build for triangle"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn build-app
  build-gh:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start build for gh-render"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn gh:build
  build-tm:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start build for todo-manager"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn tm:build
  build-cnt:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start build for counter"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn cnt:build
  build-anytn:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start build for anything"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn anytn:build
  build-at:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start build for after tutorial"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn at:build
  lint:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start lint"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lint
  stylelint:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start stylelint"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn stylelint
  test-lib:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start test for gadget"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:test:1
      - store_artifacts:
          path: coverage
  test-app:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start test for triangle"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn test-app:1
      - store_artifacts:
          path: coverage
  test-gh:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start test for gh-render"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn gh:test:1
      - store_artifacts:
          path: coverage
  test-tm:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start test for todo-manager"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn tm:test:1
      - store_artifacts:
          path: coverage
  test-cnt:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start test for counter"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn cnt:test:1
      - store_artifacts:
          path: coverage
  test-anytn:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start test for anything"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn anytn:test:1
      - store_artifacts:
          path: coverage
  test-at:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start test for after tutorial"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn at:test:1
      - store_artifacts:
          path: coverage
  e2e-app:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start e2e-app"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn e2e-app
  e2e-gh:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start e2e-gh"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn gh:e2e
  e2e-tm:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start tm:e2e"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn tm:e2e
  e2e-cnt:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start e2e-cnt"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn cnt:e2e
  e2e-anytn:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start e2e-anytn"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn anytn:e2e
  e2e-at:
    docker:
      - image: circleci/node:8.14.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start e2e-after-tutorial"
      - restore_cache:
          key: triangle-v1-{{ checksum "yarn.lock" }}
      - run: yarn lib:build
      - run: yarn at:e2e
workflows:
  version: 2
  build_and_test:
    jobs:
      - install-packages
      - build-lib:
          requires:
            - install-packages
      - build-app:
          requires:
            - build-lib
      - build-gh:
          requires:
            - build-lib
      - build-tm:
          requires:
            - build-lib
      - build-cnt:
          requires:
            - build-lib
      - build-anytn:
          requires:
            - build-lib
      - build-at:
          requires:
            - build-lib
      - build-storybook:
          requires:
            - build-lib
      - lint:
          requires:
            - build-app
      - stylelint:
          requires:
            - build-app
      - test-lib:
          requires:
            - build-lib
      - test-app:
          requires:
            - build-app
      - test-gh:
          requires:
            - build-gh
      - test-tm:
          requires:
            - build-tm
      - test-cnt:
          requires:
            - build-cnt
      - test-anytn:
          requires:
            - build-anytn
      - test-at:
          requires:
            - build-at
      - e2e-app:
          requires:
            - build-app
      - e2e-gh:
          requires:
            - build-gh
      - e2e-tm:
          requires:
            - build-tm
      - e2e-cnt:
          requires:
            - build-cnt
      - e2e-anytn:
          requires:
            - build-anytn
      - e2e-at:
          requires:
            - build-at
